"""Add image embeddings

Revision ID: beda0b0b7fb3
Revises: 3406e487f2e7
Create Date: 2026-09-13 12:08:46.099652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beda0b0b7fb3'
down_revision: Union[str, Sequence[str], None] = '3406e487f2e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('embedding', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'embedding')
    # ### end Alembic commands ###
